### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by ndelangen** [storybooks/react-storybook-addon-backgrounds#29]
I'm not sure if this package is still maintained, Do you need help?

I'm happy to integrate this into the storybook monorepo if you'd like?

There's a 3.0.0 release coming, and I'd like to make sure addons are maintained, we're willing to help where we can!

Can you join us in the storybook slack?
https://storybooks-slackin.herokuapp.com/

That way we can keep you updated on the upcoming 3.0.0 release! 

❤️ storybook team

**Comment by thuringia** [comment]
@ndelangen It appears there is no active maintainer for this addon anymore. Maybe you should fork this addon and integrate it into the monorepo.

**Comment by ndelangen** [comment]
I will try and reach out to NewSpring in another way.

**Comment by ndelangen** [comment]
I will fork it in a week or so, if needed.

**Comment by jbaxleyiii** [comment]
@ndelangen I'm SO sorry! I had notifications turned off for this!

I would love it if this was moved into the mono repo. We don't have time to maintain it. How can I help?

**Comment by ndelangen** [comment]
Can you add me as admin to this repo, I can move it over to the storybooks organisation and then merge it in! ❤️

**Comment by ndelangen** [comment]
Hey @jbaxleyiii can you let me know when you're ready?

**Comment by jbaxleyiii** [comment]
@ndelangen done!

**Comment by ndelangen** [comment]
Migrated, I will be integrating this repo in our storybook-repo soon!
